USE [master]
GO
/****** Object:  Database [EMP]    Script Date: 4/25/2021 6:18:44 PM ******/
CREATE DATABASE [EMP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EMP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\EMP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EMP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\EMP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [EMP] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EMP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EMP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EMP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EMP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EMP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EMP] SET ARITHABORT OFF 
GO
ALTER DATABASE [EMP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EMP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EMP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EMP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EMP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EMP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EMP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EMP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EMP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EMP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EMP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EMP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EMP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EMP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EMP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EMP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EMP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EMP] SET RECOVERY FULL 
GO
ALTER DATABASE [EMP] SET  MULTI_USER 
GO
ALTER DATABASE [EMP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EMP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EMP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EMP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EMP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EMP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'EMP', N'ON'
GO
ALTER DATABASE [EMP] SET QUERY_STORE = OFF
GO
USE [EMP]
GO
/****** Object:  Table [dbo].[EmployeeTable]    Script Date: 4/25/2021 6:18:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmployeeTable](
	[Empid] [int] IDENTITY(1,1) NOT NULL,
	[Empname] [nvarchar](150) NULL,
	[Email] [nvarchar](150) NULL,
	[Age] [int] NULL,
	[Salary] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Empid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [EMP] SET  READ_WRITE 
GO
